functional:
  - Регистрация пользователя
  - Авторизация с помощью сторонних сервисов
  - Вход в систему с использованием учетных данных
  - Выход из системы
  - Восстановление пароля
  - Настройка интерфейса
  - Отправка личных сообщений
  - Отправка сообщений в общий чат
  - Просмотр профиля пользователей
  - Создание батлов
  - Вступление в батл
  - Подсчет очков
  - Ведение рейтинга пользователей
non-functional:
  - Проверка пароля на надежность при регистрации
  - Совместимость с различными версиями браузеров
  - Проверка двухфакторной аутентификации
  - Время загрузки страницы не должно превышать 10 секунд
implicit:
  - Интерфейс сайта должен быть интуитивно понятным и простым в использовании для пользователей разного уровня подготовки.
  - Цветовые элементы сайта должны быть оптимизированными для экранов разных устройств
